### ISSUE TITLE
dist is lacking es5 build

### ISSUE THREAD

**Issue by vsvirydau-cl** [Odonno/ngrx-signalr-core#10]
Breaks IE < Edge
![image](https://user-images.githubusercontent.com/55260532/71380329-96d97a80-2583-11ea-8c54-b634e5f88d36.png)
![image](https://user-images.githubusercontent.com/55260532/71380338-a2c53c80-2583-11ea-9208-0517a9763513.png)

If you follow [this guide](https://angular.io/guide/creating-libraries), it sets up workspace to generate various differently compatibility builds.

**Comment by Odonno** [comment]
This project now uses the angular projet model. I should now supports both es5 and es2015.

**Comment by nicholasfaiello** [comment]
Hi - Would you be able to apply the same fix for the ngrx-signalr repository?

**Comment by Odonno** [comment]
Yep. That could be done too.

**Comment by nicholasfaiello** [comment]
That would be fantastic. Excellent library, by the way! I am impressed.

**Comment by Odonno** [comment]
Thank you!
