### ISSUE TITLE
After reconnecting - reconnected, twice events from server

### ISSUE THREAD

**Issue by pippistro-fedro** [Odonno/ngrx-signalr-core#100]
Using samples (realtime-feeds, realtime-feeds.API) testing automatic reconnection.
version 15.1.1

1. start api server
2. start angular webapp
3. stop api server
you can see webapp trying to reconnect...
4. restart api server
you can see webapp reconnect to server

but every event arriving from server create 2 actions (eg. createFeed)

If you stop and restart again, you can see after reconnect... 3 actions, and so on.

It seems that the library doesn't clean past subscriptions (imho)

**Comment by pippistro-fedro** [comment]
I think introducing a new state "reconnected" when the signalR trigger the "onreconnected" can solve the issue.

**Comment by pippistro-fedro** [comment]
I think the problem is when a reconnecting state changes to "connected": it trigger again a signalRConnected (normally used to register the events from server). 
Introducing a new state "reconnected" (like singalr librarye does) and a new relative action, it's possible avoid and differentiate the behavior.
You can see my pull request: https://github.com/Odonno/ngrx-signalr-core/pull/101

**Comment by Odonno** [comment]
This is now released in the v15.1.2

Thank you for your contribution

**Comment by pippistro-fedro** [comment]
It's a plesure, tnx for your great job.
Davide

Il ven 23 giu 2023, 22:57 David Bottiau ***@***.***> ha
scritto:
