### ISSUE TITLE
ngrx 18 compatibility

### ISSUE THREAD

**Issue by timminss** [Odonno/ngrx-signalr-core#106]
I'm updating project dependencies and have updated @ngrx/store, @ngrx/store-devtools and @ngrx/effects to version 18. Unfortunately it looks as though there is a type mismatch when attempting to use ngrx-signalr-core with v18. The error looks as follows:

'Namespace <redacted>/node_modules/@ngrx/store/src/models@ has no exported member 'TypedAction'.
(from node_modules/ngrx-signalr-core/lib/operators.d.ts:61:37)'

Is there an update to this library planned which will resolve the issue? The library has been fantastically useful in my projects and would like to stick with it if possible!

Thanks

**Comment by Odonno** [comment]
I released new versions for the latest versions of Angular including v18.

There was indeed a breaking change in Angular 18. Can you try to install the latest version and see if it works?
