### ISSUE TITLE
Please re-export actions in the main package

### ISSUE THREAD

**Issue by vsviridov** [Odonno/ngrx-signalr-core#13]
I'm currently using the `signalrHubUnstarted`, `signalrHubFailedToStart`, `signalrConnected` action types in my own effects with the `ngrx` `ofType()` operator.

After updating to the latest version, those are not available (I imported them directly via `/dist`, but now they are not available anymore).

If I try to import them via `ngrx-signalr-core/lib/actions`, it fails during build with a "cannot resolve" message.

**Comment by Odonno** [comment]
Hi Vasili, I'll check that ASAP.

**Comment by Odonno** [comment]
You now should be able to use the version 8.2.1.
