### ISSUE TITLE
Allow custom reconnectionPolicy for createReconnectEffect

### ISSUE THREAD

**Issue by tscislo** [Odonno/ngrx-signalr-core#21]
I'd like to create PR for this repo with following change to createReconnectEffect. Please have a look @Odonno and let me know how can I create PR?

**Basically - purpose of it is to limit retryTimes, also isOnline validation is done before each retry, as there is no point in reconnecting when browser is offline.**

```ts
export const createReconnectEffect = (actions$: Actions<Action>, intervalTimespan: number, retryTimes: number = 10) => {
  return createEffect(() =>
    actions$.pipe(
      ofType(signalrDisconnected),
      groupBy(action => action.hubName),
      mergeMap(group =>
        group.pipe(
          exhaustMapHubToAction(({action}) => {
              return timer(0, intervalTimespan)
                .pipe(
                  switchMap(isOnline),
                  filter((is) => is),
                  take(retryTimes),
                  map(_ => reconnectSignalRHub(action)),
                  takeUntil(
                    this.actions$.pipe(
                      ofType(signalrConnected),
                      ofHub(action)
                    )
                  )
                );
            }
          )
        )
      )
    )
  );
};
```

**Comment by Odonno** [comment]
Well, I see what got you here.

I already refactored the `createReconnectEffect` function, using an `options` as 2nd parameter.
But now what I would want is to allow devs to trigger the reconnection by themselves, using their own implementation. That was what I first intended but not knowing the best way to do it.

Now that I see more clearly, I would suggest to add another property in the `options` called `triggerReconnection$` which would be an Observable.

If the Observable is not provided, I will use the default implementation (current one). What do you think?

**Comment by tscislo** [comment]
In order to currently achieve above mentioned result (limiting number of retries) I had to copy this whole implementation of effect into my source code. So with what you're proposing (triggerReconnection$) every dev would also need to copy lot of boilerplate code (things that always will be needed: ofType, groupBy, etc). 

Therefore my proposal is to have options passed like this (let's have both):
```ts
{
intervalTimespan
retryTimes,
triggerReconnection$
}
`

Which would allow to have completely custom triggerReconnection strategy for those who want and to have fully working, yet customizable strategy for those who want it out of the box, agreed?

**Comment by Odonno** [comment]
Ah sorry.

The `triggerReconnection$` will only be inside the `exhaustMapHubToAction`. So it will look like this:

```ts
export const createReconnectEffect = (actions$: Actions<Action>, options) => {
  return createEffect(() =>
    actions$.pipe(
      ofType(signalrDisconnected),
      groupBy(action => action.hubName),
      mergeMap(group =>
        group.pipe(
          exhaustMapHubToAction(({action}) => {
              return options.triggerReconnection$
                .pipe(
                  map(_ => reconnectSignalRHub(action)),
                  takeUntil(
                    this.actions$.pipe(
                      ofType(signalrConnected),
                      ofHub(action)
                    )
                  )
                );
            }
          )
        )
      )
    )
  );
};
```

**Comment by Odonno** [comment]
I just edited my code to you a function instead. Of course you could create a custom reconnection strategy based on the hub (based on the disconnected action previously dispatched).

**Comment by tscislo** [comment]
Ok in that case, that's all we need I guess. Will you progress with those changes?

**Comment by Odonno** [comment]
I will do it right now :)

**Comment by Odonno** [comment]
Done.

You should see the v8.4.0 now.
Tell me what you think!

**Comment by tscislo** [comment]
Yes, that works as expected. Thank you!

**Comment by tscislo** [comment]
@Odonno comming back to this old issue ;)
Let's say that I have such reconnectionPolicy
```
private whenDisconnected$ = createReconnectEffect(this.actions$, {
    reconnectionPolicy: () =>
      timer(0, this.reconnectTimeout).pipe(
        switchMap(isOnline$),
        filter((isOnline) => isOnline),
        take(this.failedReconnectAttempts)
      )
  });
```
Unfortunataly sometimes my berer token that I use to authenticate my negotiate endoint changes
```
 createHub(): void {
    this.auth
      .getAccessTokenSilently({ignoreCache: true})
      .pipe(take(1))
      .subscribe((token) => {
        this.hub.options = {
          accessTokenFactory: () => token
        };
        this.store.dispatch(createSignalRHub(this.hub));
      });
  }
```
Is there any way I can trigger accessTokenFactory and refres this token in reconnectionPolicy?
