### ISSUE TITLE
IllegalInvocation Error

### ISSUE THREAD

**Issue by vsvirydau-cl** [Odonno/ngrx-signalr-core#3]
Hello, I've read the [article](https://medium.com/@dbottiau/simplify-your-realtime-applications-by-bringing-signalr-into-the-ngrx-ecosystem-bc984cf2800c), but it's not entirely clear where all those things go in an actual app...

I've tried to do the following:
```
export class RealtimeEffectsService implements OnInitEffects {
  constructor(private actions$: Actions) { }

  ngrxOnInitEffects() {
    const hub = {...};
    return createSignalRHub(hub);
  }

  initRealTime$ = createEffect(() =>
    this.actions$.pipe(
      ofType(SIGNALR_HUB_UNSTARTED),
      mergeMapHubToAction(({hub}) => {
/// basically set up from the article
      })
    ),
  );
}
```

but if I return `merge(of(startSignalRHub...` in that effect - my application crashes with `Subscription.js:23 Uncaught TypeError: Cannot assign to read only property 'closed' of object`

Where do you normally put the logic described in the article?

**Comment by vsvirydau-cl** [comment]
Ended up adding another effect in the same service and switching the effect that handles signalr messages to a non-dispatching one.

```
attachRealTime$ = createEffect(() =>
  this.actions$.pipe(
    ofType(signalrHubUnstarted),
    map(startSignalRHub),
  ),
);
```

**Comment by Odonno** [comment]
Well, the thing is that if you stay with your current version of `attachRealTime$` effect, you will only start the hub without listening to any server->client events. But, if you only care about sending messages client->server, then you won't need anything else. It depends on what you want to do with your hub.

About your previous error, it's unclear what went wrong. I never experienced any issue with this code. Are you able to share a repoduction project so I can take a look?

Anyway, I am sorry if the article isn't crystal clear. I think my next step would be to provide a concrete example application that I will host on this repository.

**Comment by vsvirydau-cl** [comment]
Hmm, it does listen to events... I've set them up in a separate effect that doesn't dispatch.

I've tried setting up a repro in StackBlitz, but for some reason it is being a total pain.
I'll try CodeSandbox

Having a concrete example would be great!

**Comment by Odonno** [comment]
Oh. Right. Never thought of that. So, you listen to the `signalrHubUnstarted` action in 2 different effects and you listen to events in the first one and you start the hub in the second one? Seems great.

**Comment by vsvirydau-cl** [comment]
https://cssbp.csb.app/

I hope this works... I think if `strictStateImmutability` and `strictActionImmutability` are both set for the `ngrx/store` - then the issue manifests itself

**Comment by Odonno** [comment]
Oh. I see. It seems that you always need a new action due to `strictActionImmutability` option. So, you need to do that instead:

```
return merge(hubEvents$, of(startSignalRHub(
    { ...hub }
)));
```

**Comment by Odonno** [comment]
Or, it seems that this works even better: 

```
return merge(
    hubEvents$,
    of(startSignalRHub({ hubName: hub.hubName, url: hub.url }))
);
```

**Comment by vsvirydau-cl** [comment]
Let me try that.

**Comment by vsvirydau-cl** [comment]
This works. Thanks.
