### ISSUE TITLE
withAutomaticReconnect

### ISSUE THREAD

**Issue by GeorgBreithaupt** [Odonno/ngrx-signalr-core#37]
Would it be possible to activate "withAutoReconnect" when creating the connection? Or is there a special reason why this doesn't work?

Many Thanks!

```
export const createConnection = (
  url: string,
  options?: IHttpConnectionOptions | undefined
) => {
  if (!options) {
    return new HubConnectionBuilder().withUrl(url).build();
  }

  return new HubConnectionBuilder()
	.withUrl(url, options)
	.withAutomaticReconnect()
	.build();
};
```

**Comment by Odonno** [comment]
Hi @GeorgBreithaupt 

If I remember correctly, this feature was not part of the first versions. Of course, since it is now part of the library, we can support this feature.

**Comment by Odonno** [comment]
v14.1.0 is now available with automatic reconnect feature. You can check the readme file to see how to use it.
