### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by Odonno** [Odonno/ngrx-signalr-core#5]

**Comment by zeroregard** [comment]
Seconding this, it would be quite nice

**Comment by Odonno** [comment]
I seek a project idea that can fit this description:

* small project
* full-stack app (frontend + backend)
* handle a collection of items (so we can show how to use @ngrx/entity with ngrx-signalr)
* has at a least a realtime feature (realtime data updated)

Does anyone have an idea?

**Comment by mtinnes** [comment]
Just something like a starter framework to show how the parts fit together. Doesn't need to do anything complicated I wouldn't think. Nice work!

**Comment by Odonno** [comment]
Ok. I made the simplest possible example app. You can now find in this repository. here are the specs:

* full-stack web app of realtime feeds (new feed created every 10s)
* ASP.NET Core 3.1 Web API (using SignalR obviously)
  * `feedsLoaded` event (collection of feeds)
  * `feedCreated` event (when a feed is created)
* Angular 9 app
  * @ngrx packages and ngrx-signalr-core integration
  * handle state management of collection of feeds with @ngrx/entity

I hope you'll like it.
