### ISSUE TITLE
withHubProtocol

### ISSUE THREAD

**Issue by wouth** [Odonno/ngrx-signalr-core#84]
Like the "withAutoReconnect", would it be possible to activate "withHubProtocol" when creating the connection?

```
new HubConnectionBuilder()
.withUrl(url, options)
.withHubProtocol(new MessagePackHubProtocol())
.build()
```

**Comment by wouth** [comment]
Just created this PR: https://github.com/Odonno/ngrx-signalr-core/pull/85

**Comment by Odonno** [comment]
v14.2.0 is now available with the new feature. Enjoy!!
